apiVersion: apps/v1
kind: Deployment
metadata:
 name: greenthumbs
 labels:
   app: greenthumbs
spec:
 replicas: 3
 selector:
   matchLabels:
     app: greenthumbs
 template:
   metadata:
     labels:
       app: greenthumbs
   spec:
     containers:
     - name: greenthumbs
       image: icr.io/greenthumbs/project:1.0
       ports:
       - containerPort: 5000
